### PR TITLE
Update hyperkit go module

### PR DESCRIPTION
**Pull request by cfergeau**
Latest version of the hyperkit go module should make it easier to support disk resizing on macos.
In order to do this update, misc changes are needed in the hyperkit machine driver, the main one being that we can no longer use hyperkit.json to get the hyperkit pid as it can't be unserialized.
This is why this PR starts with a rework of the pid reading code to make it use hyperkit.pid rather than hyperkit.json.

After this update, we need to modify crc to make it install qcow-tool, and pass its path to the machine driver. This should be 90% of what is needed for disk resizing to work (assuming qcow-tool can handle our images)

This PR should not have any user visible changes, starting/stopping the VM should be exactly the same as before, especially in corner cases.

### CODE REVIEW

**Comment by guillaumerose** [comment]
The linter is failing on my machine. Otherwise lgtm!

**Comment by cfergeau** [comment]
It's fine here with `golangci-lint has version v1.37.1`

**Comment by guillaumerose** [comment]
```
$  ~/Downloads/golangci-lint-1.37.1-darwin-amd64/golangci-lint run
pkg/hyperkit/driver.go:43:2: `machineFileName` is unused (deadcode)
	machineFileName = "hyperkit.json"
	^
pkg/hyperkit/driver.go:245:10: `if` block ends with a `return` statement, so drop this `else` and outdent its block (golint)
		} else {
		       ^
```

weird :/

**Comment by cfergeau** [comment]
> ```
> $  ~/Downloads/golangci-lint-1.37.1-darwin-amd64/golangci-lint run
> pkg/hyperkit/driver.go:43:2: `machineFileName` is unused (deadcode)
> 	machineFileName = "hyperkit.json"
> 	^
> pkg/hyperkit/driver.go:245:10: `if` block ends with a `return` statement, so drop this `else` and outdent its block (golint)
> 		} else {
> 		       ^
> ```
> 
> weird :/

Ah, I was running the test on linux, and `driver.go` starts with `// +build darwin`. I get the same errors if I run golangci-lint on macos

**Pull request merged**
